services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  migrate:
    build: ./api
    depends_on:
      - db
    entrypoint: ["sh", "-c", "npx prisma migrate deploy"]

  api:
    build: ./api
    restart: unless-stopped
    depends_on:
      - db
      - migrate
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${PORT}:${PORT}"

  app:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "5173:5173"
