services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"

  migrate:
    build: ./api
    depends_on:
      - db

  api:
    build: ./api
    restart: unless-stopped
    depends_on:
      - db
      - migrate
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    expose:
      - "3000"

  app:
    build: ./frontend
    depends_on:
      - api
    environment:
      VITE_API_URL: ${VITE_API_URL}
