services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${NODE_ENV}konekta:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  devkonekta:
  testkonekta:
  prodkonekta:
